sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "7.1"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - npm install -g angular-cli
  - npm install -g node-gyp
  - npm install -g @angular/cli
  - npm install -g karma
script:
  - ng test -sr
  - ng e2e
  - ng build --prod
